//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Clinique_dbEntities : DbContext
    {
        public Clinique_dbEntities()
            : base("name=Clinique_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActePose> ActePoses { get; set; }
        public virtual DbSet<Compte> Comptes { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Equivalence> Equivalences { get; set; }
        public virtual DbSet<FamilleActe> FamilleActes { get; set; }
        public virtual DbSet<Fiche> Fiches { get; set; }
        public virtual DbSet<LibelleActe> LibelleActes { get; set; }
        public virtual DbSet<Medicament> Medicaments { get; set; }
        public virtual DbSet<Nature> Natures { get; set; }
        public virtual DbSet<Parametre> Parametres { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Personnel> Personnels { get; set; }
        public virtual DbSet<Planning> Plannings { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<RendezVou> RendezVous { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VenteMedicament> VenteMedicaments { get; set; }
    }
}
